spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_list?currentSchema=task_list
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
#      data-locations: classpath:demo_data.sql
security:
  jwt:
    secret: a2pzZGRnaGh2LGRtZmJhbGtqYmphZmJrcic7bmEgLCdlbWI7ZWFqaHJnaWhhZWk7b3Z1c2F2ay8uYW1ibHRyd2hp
    access: 3600000
    refresh: 2592000000
